### ISSUE TITLE
Error in Graph at Assets/Toon-Shader-master/Awesome Toon/AwesomeToon.shadergraph at node AwesomeToon Sub: Could not find Sub Graph asset with GUID af8ea54a097adc649ac95deb23fbf291

### ISSUE THREAD

**Issue by bslayerw** [SnutiHQ/Toon-Shader#4]
Unity 2020.1.3.f1 
URP. 

After downloading the as a zip from github and importing into my project I get the following error. 

Error in Graph at Assets/Toon-Shader-master/Awesome Toon/AwesomeToon.shadergraph at node AwesomeToon Sub: Could not find Sub Graph asset with GUID af8ea54a097adc649ac95deb23fbf291.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

**Comment by ecker00** [comment]
This error is described how to fix here → https://github.com/SnutiHQ/Toon-Shader#troubleshoot

Unity doesn't keep the link between these files between projects, could maybe have been solved by including the `.meta` files.
